name: Terraform on DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.7

      - name: Terraform Initialize
        run: |
          terraform init -reconfigure \
            -backend-config="access_key=${{ secrets.SPACES_ACCESS_KEY }}" \
            -backend-config="secret_key=${{ secrets.SPACES_SECRET_KEY }}"

      - name: Terraform Plan
        run: terraform plan -var "do_token=${{ secrets.DO_TOKEN }}" -var "github_token=${{ secrets.GH_TOKEN }}"

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve -var "do_token=${{ secrets.DO_TOKEN }}" -var "github_token=${{ secrets.GH_TOKEN }}"
